import { buildEquityAward } from "../../vesting_schedule_generator/tests/equity-award-builder";

export const ocfPackage = buildEquityAward([
  {
    id: "ES-1",
    grantDate: "2017-11-07",
    stakeholderId: "HarryPotter",
    quantity: 23138,
    exercisePrice: 0.27,
    vestingTermsConfig: {
      id: "2-year-monthly-no-cliff",
      installmentCount: 24,
      monthsPerInstallment: 1,
      cliff_installment: 0,
    },
    VCD: "2017-02-13",
    earlyExercisable: true,
    NSO: true,
  },
  {
    id: "ES-2",
    grantDate: "2020-09-09",
    stakeholderId: "HarryPotter",
    quantity: 290000,
    exercisePrice: 0.77,
    vestingTermsConfig: {
      id: "4-year-monthly-1-year-cliff",
      installmentCount: 48,
      monthsPerInstallment: 1,
      cliff_installment: 12,
    },
    VCD: "2020-06-29",
    earlyExercisable: true,
  },
  {
    id: "ES-3",
    grantDate: "2020-09-09",
    stakeholderId: "HarryPotter",
    quantity: 10000,
    exercisePrice: 0.77,
    vestingTermsConfig: {
      id: "4-year-monthly-no-cliff",
      installmentCount: 48,
      monthsPerInstallment: 1,
      cliff_installment: 0,
    },
    VCD: "2020-01-16",
    earlyExercisable: true,
  },
  {
    id: "ES-4",
    grantDate: "2021-05-11",
    stakeholderId: "HarryPotter",
    quantity: 101000,
    exercisePrice: 0.77,
    vestingTermsConfig: {
      id: "4-year-monthly-no-cliff",
      installmentCount: 48,
      monthsPerInstallment: 1,
      cliff_installment: 0,
    },
    VCD: "2021-05-07",
  },
  {
    id: "ES-5",
    grantDate: "2022-07-15",
    stakeholderId: "HarryPotter",
    quantity: 52857,
    exercisePrice: 1.38,
    vestingTermsConfig: {
      id: "1-year-monthly-no-cliff",
      installmentCount: 12,
      monthsPerInstallment: 1,
      cliff_installment: 0,
    },
    VCD: "2022-06-28",
  },
  {
    id: "ES-6",
    grantDate: "2023-04-10",
    stakeholderId: "HarryPotter",
    quantity: 310000,
    exercisePrice: 1.96,
    vestingTermsConfig: {
      id: "4-year-monthly-no-cliff",
      installmentCount: 48,
      monthsPerInstallment: 1,
      cliff_installment: 0,
    },
    VCD: "2023-04-10",
  },
]);
